# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.4.6
_src_path: https://github.com/epics-containers/ioc-template
description: A generic IOC with ADCore support, for use as a base image for detectors
git_platform: github.com
github_org: epics-containers
name: ioc-areadetector
repo_uri: git@github.com:epics-containers/ioc-areadetector.git
rtems: false
